name = "telegram-github-webhook"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
TELEGRAM_CHAT_ID = "623447167905824769"

# Secrets to set via CLI:
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put WEBHOOK_SECRET
